### ISSUE TITLE
crashed in method hide()

### ISSUE THREAD

**Issue by fg2q1q3q** [fayaz07/progress_dialog#13]
After updating the flutter SDK to the latest version, the` hide() `method crashes. Specifically pointing to this line: `Navigator.of(_context).pop();`my code is exactly the same as the example, error reporting information is as follows：
```
NoSuchMethodError (NoSuchMethodError: The method 'ancestorStateOfType' was called on null.
Receiver: null
Tried calling: ancestorStateOfType(Instance of 'TypeMatcher<NavigatorState>'))
```

**Comment by dexcell** [comment]
same issue, to reproduce put the hide inside catch block. (try catch)

**Comment by dexcell** [comment]
These code below will reproduce the issue
````
var progressDialog = ProgressDialog(context, ProgressDialogType.Normal);
progressDialog.setMessage('Loading..');
progressDialog.show();
try {
 throw Exception('Something Error');
} catch (e) {
 progressDialog.hide();
}
````
It turned out that `hide()` function is called before `showDialog` inside `show()` function complete. Workaround at the moment, we can use future delayed to hide the progress dialog, but maybe `show()` function should have return future, so we can use await to make sure the dialog is created.

**Comment by fg2q1q3q** [comment]
I found the answer to the question, because I initialized it in the build method of state, and changed it to initState and the problem no longer appeared.
