### ISSUE TITLE
Show dialog and then hide and then just show it again, and you can't hide it

### ISSUE THREAD

**Issue by yousaywhat** [fayaz07/progress_dialog#34]
pr.show();
pr.dismiss();
pr.show();
pr.dismiss();
But the dialog shown a second time cannot be hidden

**Comment by fayaz07** [comment]
code

**Comment by jam33** [comment]
this is happening for me too.  i'll try to get some code that illustrates the problem, but thought for now I would confirm I'm experiencing this too (with the latest version of everything).

**Comment by yousaywhat** [comment]
@fayaz07  
I have a list, similar to a network backup folder, display dialog before access to the data, access to the data behind the dialog, click on one list of entries, the directory into the next layer, and access to the data before the show, after the access to the data hiding, if at the moment the first hidden layer dialog click on to the next layer, so the dialog cannot be hidden

**Comment by yousaywhat** [comment]
![image](https://user-images.githubusercontent.com/16442633/68988384-69f1c380-0871-11ea-9fc0-a84325c4d73d.png)

**Comment by yousaywhat** [comment]
![image](https://user-images.githubusercontent.com/16442633/68988388-7bd36680-0871-11ea-9bf2-fefbf5c6055a.png)

**Comment by fayaz07** [comment]
post the log please, which is causing the issue

**Comment by yousaywhat** [comment]
There is no error message, but the dialog cannot hide it @fayaz07

**Comment by fayaz07** [comment]
try using the code in a try-catch block

**Comment by yousaywhat** [comment]
I tried, but didn't report any errors, so I couldn't walk catch

**Comment by yousaywhat** [comment]
The first Dialog is indeed hidden, but if the second Dialog is opened instantly, the second Dialog cannot be hidden

**Comment by fayaz07** [comment]
then that's not the issue of progress_dialog you have to configure it properly
you can continue until the process is done, rather than hiding and again showing it right?

**Comment by yousaywhat** [comment]
No, I've tried them, show this dialog before to get the data, after the access to the data hiding, if in the hidden moments to get the data again, show the dialog, then the second dialog will always exist, I couldn't think of what went wrong, I'm just in the hidden moment only let him once again shows the dialog, you can try this logic, add a delay to hide

**Comment by fayaz07** [comment]
> pr.show();
> pr.dismiss();
> pr.show();
> pr.dismiss();
> But the dialog shown a second time cannot be hidden

hide and show methods are futures, wait for them to get executed first

**Comment by BjoernPetersen** [comment]
> hide and show methods are futures, wait for them to get executed first

The show method is not a future.

**Comment by fayaz07** [comment]
yeah @BjoernPetersen  that's my bad I will fix it

**Comment by ms747** [comment]
@fayaz07 Any updates? I'm having the same issue. Thanks

**Comment by davbaron** [comment]
I had a similar issue, albeit for different reasons. In my case, I have a 'sign in' screen that executes, and upon success, closes (pops) and informs 'the rest of the app' (via ScopedModel) that the user has signed in, which results in the underlying screen to 'react' by calling a web api to fetch data for display on that screen. Though the 'show/hide' couplets are on separate screens, they 'act' in the same way:  show/hide, then show/hide. My problem was that the second 'hide' was not working.

I had already downloaded the code so that I could modify it quite a bit (adding auto-close and auto-width determination based on message length, for example), and was able to debug enough to find 'what' was happening, and then 'why' it was happening.

The 'what' was due to timing.  Here's what really happens, in sequence:  Show instance 1... Hide instance 1 (which sets _isShowing to false).... Show instance 2 (which sets _isShowing to true)...  DISPOSE instance 1 (which sets _isShowing to false... Hide instance 2, which *fails* since it checks the _isShowing value, which is currently false!  In other words, even though the first dlog was closed, it took some time for the Dispose method to get called... and during that time, the second instance was opened!

The 'why' is more problematic.  The add-in makes use of a bunch of 'global variables'.  I am not even sure what the proper name for these are:  they are variables that are defined *above* the class definition itself.  That means they are essentially *shared* between instances of the dlog. Thus, using the example I've laid out, the 1st instance 'hides', setting _isShowing to false... the 2nd instance 'shows', setting _isShowing to true, but then the 1st instance, which is still 'alive', Disposes, setting _isShowing to false.  When the 2nd instance tries to hide, it finds that _isShowing is false (due to being set by 1st instance as it Disposed), and so it does nothing.

I'm guessing the author did not anticipate multiple concurrent or 'near-time' instances of the dialog being opened/closed. The common-shared variables is not the best approach for those use-cases.

In my own copy of the code, I have moved those common-shared vars into the class definition of the ProgressDialog.  I also pass a bunch of them 'into' the _Body stateful widget via both the _Body's constructor and .Update methods (so that they become 'widget.XYZ' attributes. Finally I had to pass the current BuildContext value into the .Show method to get things fully working. 

@fayaz07, @yousaywhat and @ms747 please let me know if this makes sense, and if you'd like a copy of the fixed code. I have not done a proper 'pull' and do not have the code in a public repository at this time.

**Comment by sidvenu** [comment]
```
I/flutter (11497): ProgressDialog shown
I/flutter (11497): ProgressDialog dismissed by back button
I/flutter (11497): ProgressDialog already dismissed
```
The 2nd log happens between showing it and calling `dismiss()`. Thus, in `dismiss()` method, `isShowing = false` and thus, says it is already dismissed, though it hasn't been removed from the screen.

**Comment by fajarainul** [comment]
> I had a similar issue, albeit for different reasons. In my case, I have a 'sign in' screen that executes, and upon success, closes (pops) and informs 'the rest of the app' (via ScopedModel) that the user has signed in, which results in the underlying screen to 'react' by calling a web api to fetch data for display on that screen. Though the 'show/hide' couplets are on separate screens, they 'act' in the same way: show/hide, then show/hide. My problem was that the second 'hide' was not working.
> 
> I had already downloaded the code so that I could modify it quite a bit (adding auto-close and auto-width determination based on message length, for example), and was able to debug enough to find 'what' was happening, and then 'why' it was happening.
> 
> The 'what' was due to timing. Here's what really happens, in sequence: Show instance 1... Hide instance 1 (which sets _isShowing to false).... Show instance 2 (which sets _isShowing to true)... DISPOSE instance 1 (which sets _isShowing to false... Hide instance 2, which _fails_ since it checks the _isShowing value, which is currently false! In other words, even though the first dlog was closed, it took some time for the Dispose method to get called... and during that time, the second instance was opened!
> 
> The 'why' is more problematic. The add-in makes use of a bunch of 'global variables'. I am not even sure what the proper name for these are: they are variables that are defined _above_ the class definition itself. That means they are essentially _shared_ between instances of the dlog. Thus, using the example I've laid out, the 1st instance 'hides', setting _isShowing to false... the 2nd instance 'shows', setting _isShowing to true, but then the 1st instance, which is still 'alive', Disposes, setting _isShowing to false. When the 2nd instance tries to hide, it finds that _isShowing is false (due to being set by 1st instance as it Disposed), and so it does nothing.
> 
> I'm guessing the author did not anticipate multiple concurrent or 'near-time' instances of the dialog being opened/closed. The common-shared variables is not the best approach for those use-cases.
> 
> In my own copy of the code, I have moved those common-shared vars into the class definition of the ProgressDialog. I also pass a bunch of them 'into' the _Body stateful widget via both the _Body's constructor and .Update methods (so that they become 'widget.XYZ' attributes. Finally I had to pass the current BuildContext value into the .Show method to get things fully working.
> 
> @fayaz07, @yousaywhat and @ms747 please let me know if this makes sense, and if you'd like a copy of the fixed code. I have not done a proper 'pull' and do not have the code in a public repository at this time.

nice explanation, thanks!

**Comment by fajarainul** [comment]
> I had a similar issue, albeit for different reasons. In my case, I have a 'sign in' screen that executes, and upon success, closes (pops) and informs 'the rest of the app' (via ScopedModel) that the user has signed in, which results in the underlying screen to 'react' by calling a web api to fetch data for display on that screen. Though the 'show/hide' couplets are on separate screens, they 'act' in the same way: show/hide, then show/hide. My problem was that the second 'hide' was not working.
> 
> I had already downloaded the code so that I could modify it quite a bit (adding auto-close and auto-width determination based on message length, for example), and was able to debug enough to find 'what' was happening, and then 'why' it was happening.
> 
> The 'what' was due to timing. Here's what really happens, in sequence: Show instance 1... Hide instance 1 (which sets _isShowing to false).... Show instance 2 (which sets _isShowing to true)... DISPOSE instance 1 (which sets _isShowing to false... Hide instance 2, which _fails_ since it checks the _isShowing value, which is currently false! In other words, even though the first dlog was closed, it took some time for the Dispose method to get called... and during that time, the second instance was opened!
> 
> The 'why' is more problematic. The add-in makes use of a bunch of 'global variables'. I am not even sure what the proper name for these are: they are variables that are defined _above_ the class definition itself. That means they are essentially _shared_ between instances of the dlog. Thus, using the example I've laid out, the 1st instance 'hides', setting _isShowing to false... the 2nd instance 'shows', setting _isShowing to true, but then the 1st instance, which is still 'alive', Disposes, setting _isShowing to false. When the 2nd instance tries to hide, it finds that _isShowing is false (due to being set by 1st instance as it Disposed), and so it does nothing.
> 
> I'm guessing the author did not anticipate multiple concurrent or 'near-time' instances of the dialog being opened/closed. The common-shared variables is not the best approach for those use-cases.
> 
> In my own copy of the code, I have moved those common-shared vars into the class definition of the ProgressDialog. I also pass a bunch of them 'into' the _Body stateful widget via both the _Body's constructor and .Update methods (so that they become 'widget.XYZ' attributes. Finally I had to pass the current BuildContext value into the .Show method to get things fully working.
> 
> @fayaz07, @yousaywhat and @ms747 please let me know if this makes sense, and if you'd like a copy of the fixed code. I have not done a proper 'pull' and do not have the code in a public repository at this time.

@davbaron can you post your solution??

**Comment by davbaron** [comment]
You can PM me at david dash baron at em es en dot com.

**Comment by fernando-s97** [comment]
@davbaron I was unable to interpret your email. Can you please try to re-pass?
